In [1]:
import tensorflow as tf
import keras

In [2]:
import pandas as pd
import sklearn
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = ["the glass of milk",
        "the glass of juice",
        "the cup of tea",
        "I am a good boy",
        "I am a good developer",
        "understand the meaning of words",
        "your videos are good"]

In [4]:
voc_size=10000 #vector range

In [5]:
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6034, 4614, 8511, 2708],
 [6034, 4614, 8511, 7110],
 [6034, 1929, 8511, 3938],
 [8403, 587, 902, 2906, 8316],
 [8403, 587, 902, 2906, 306],
 [2449, 6034, 3955, 8511, 6336],
 [7692, 6559, 6208, 2906]]

In [6]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np
sent_len = 8
#making every sentence equal to max length - 8 by adding 0's to pre or post sentence vectors
embedded_docs = pad_sequences(one_hot_repr,padding="pre",maxlen=sent_len)
embedded_docs

array([[   0,    0,    0,    0, 6034, 4614, 8511, 2708],
       [   0,    0,    0,    0, 6034, 4614, 8511, 7110],
       [   0,    0,    0,    0, 6034, 1929, 8511, 3938],
       [   0,    0,    0, 8403,  587,  902, 2906, 8316],
       [   0,    0,    0, 8403,  587,  902, 2906,  306],
       [   0,    0,    0, 2449, 6034, 3955, 8511, 6336],
       [   0,    0,    0,    0, 7692, 6559, 6208, 2906]])

In [8]:
##feature representation
dim=10

In [9]:
model=Sequential()

model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.build(input_shape=(None, sent_len))
model.compile(optimizer="adam", loss="mse")

In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[[-0.0023424 ,  0.03320247, -0.0332189 ,  0.01934563,
         -0.0233559 , -0.03265374,  0.00013893,  0.00844332,
         -0.04185979,  0.02031138],
        [-0.0023424 ,  0.03320247, -0.0332189 ,  0.01934563,
         -0.0233559 , -0.03265374,  0.00013893,  0.00844332,
         -0.04185979,  0.02031138],
        [-0.0023424 ,  0.03320247, -0.0332189 ,  0.01934563,
         -0.0233559 , -0.03265374,  0.00013893,  0.00844332,
         -0.04185979,  0.02031138],
        [-0.0023424 ,  0.03320247, -0.0332189 ,  0.01934563,
         -0.0233559 , -0.03265374,  0.00013893,  0.00844332,
         -0.04185979,  0.02031138],
        [ 0.01191747,  0.00620721,  0.03390025,  0.04966011,
          0.04746884, -0.01219815, -0.03579652,  0.01023276,
         -0.01575112,  0.01237436],
        [ 0.00502085, -0.04008893, -0.02019076,  0.04787061,
         -0.02530539, -0.01743428,  0.02427684,  0.03517524,
         -0.04494946, -0.01865141],
        [ 0.03721044,  0.01295668, -0.04339762, -0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 6034, 4614, 8511, 2708])